import {
  mobile,
  backend,
  creator,
  web,
  javascript,
  typescript,
  html,
  css,
  reactjs,
  redux,
  tailwind,
  nodejs,
  mongodb,
  git,
  figma,
  // docker,
  // meta,
  // starbucks,
  // tesla,
  // shopify,
  crowdimage,
  healthcare,
  miimage,
  netfliximage,
  tripguide,
  volunteerimage,
  threejs,
} from "../assets";

export const navLinks = [
  {
    id: "about",
    title: "About",
  },
  {
    id: "work",
    title: "Work",
  },
  {
    id: "contact",
    title: "Contact",
  },
];

const services = [
  {
    title: "Web Developer",
    icon: web,
  },
  {
    title: "3D Animator",
    icon: mobile,
  },
  {
    title: "Backend Developer",
    icon: backend,
  },
  {
    title: "Content Creator",
    icon: creator,
  },
];

const technologies = [
  {
    name: "HTML 5",
    icon: html,
  },
  {
    name: "CSS 3",
    icon: css,
  },
  {
    name: "JavaScript",
    icon: javascript,
  },
  {
    name: "TypeScript",
    icon: typescript,
  },
  {
    name: "React JS",
    icon: reactjs,
  },
  {
    name: "Redux Toolkit",
    icon: redux,
  },
  {
    name: "Tailwind CSS",
    icon: tailwind,
  },
  {
    name: "Node JS",
    icon: nodejs,
  },
  {
    name: "MongoDB",
    icon: mongodb,
  },
  {
    name: "Three JS",
    icon: threejs,
  },
  {
    name: "git",
    icon: git,
  },
  {
    name: "figma",
    icon: figma,
  },
  // {
  //   name: "docker",
  //   icon: docker,
  // },
];

const experiences = [
  {
    title: "Video Editor",
    company_name: "Youtub Channel",
    icon: creator,
    iconBg: "#383E56",
    date: "December 2021 - july 2022",
    points: [
      "Edited video for a client for his youtube channel.",
      "Collaborated with other video editor and worked in a team.",
    ],
  },
  {
    title: "fresher",
    company_name: "",
    icon: web,
    iconBg: "#383E56",
    date: "",
    points: [
      "looking for the great opportunity.",
      "have strong understanding of DSA.",
      "Good at working with teams",
    ],
  },
];

const testimonials = [
  {
    testimonial:
      "I thought it was impossible to make a website as beautiful as our product, but Rick proved me wrong.",
    name: "Sara Lee",
    designation: "CFO",
    company: "Acme Co",
    image: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    testimonial:
      "I've never met a web developer who truly cares about their clients' success like Rick does.",
    name: "Chris Brown",
    designation: "COO",
    company: "DEF Corp",
    image: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    testimonial:
      "After Rick optimized our website, our traffic increased by 50%. We can't thank them enough!",
    name: "Lisa Wang",
    designation: "CTO",
    company: "456 Enterprises",
    image: "https://randomuser.me/api/portraits/women/6.jpg",
  },
];

const projects = [
  {
    name: "Healthcare Management",
    description:
      "Healthcare Management platform that allows patients to register, manage medical information, and book appointments. Administrators can manage appointments and send SMS notifications.",
    tags: [
      {
        name: "nextjs",
        color: "blue-text-gradient",
      },
      {
        name: "appwrite",
        color: "green-text-gradient",
      },
      {
        name: "Shadcn/ui",
        color: "pink-text-gradient",
      },
    ],
    image: healthcare,
    source_code_link: "https://github.com/shashi4263/healthcare_carepulse",
  },
  {
    name: "Decentralized Crowdfunding",
    description:
      "Web3-based decentralized platform that allows users to create campaign, donate, and manage campaign generated by users, providing a transparent and efficient solution for crowdfunding with blockchain technology.",
    tags: [
      {
        name: "react",
        color: "blue-text-gradient",
      },
      {
        name: "thirdweb",
        color: "green-text-gradient",
      },
      {
        name: "blockchain",
        color: "pink-text-gradient",
      },
    ],
    image: crowdimage,
    source_code_link: "https://github.com/shashi4263/Crowdfunding",
  },
  {
    name: "MI clone",
    description:
      "Web application that enables users to search for items, view cost, and and wonderful UI.",
    tags: [
      {
        name: "react",
        color: "blue-text-gradient",
      },
      {
        name: "tailwindcss",
        color: "green-text-gradient",
      },
      {
        name: "clone",
        color: "pink-text-gradient",
      },
    ],
    image: miimage,
    source_code_link: "https://github.com/shashi4263/MiStore-clone",
  },
  {
    name: "Netflix clone",
    description:
      "A Netflix clone built using Next.js and various modern web development tools, including React, Supabase, Next-Auth, Prisma, Tailwind.css, and Shadcn/UI.",
    tags: [
      {
        name: "react",
        color: "blue-text-gradient",
      },
      {
        name: "tailwindcss",
        color: "green-text-gradient",
      },
      {
        name: "clone",
        color: "pink-text-gradient",
      },
    ],
    image: netfliximage,
    source_code_link: "https://github.com/shashi4263/netflix-clone",
  },
  {
    name: "Volunteer",
    description:
      "A volunteer project built with the MERN stack, aimed at providing a platform for people to donate money for those in need. It includes a user-friendly interface with a navbar, homepage, donation page, and contact page.",
    tags: [
      {
        name: "react",
        color: "blue-text-gradient",
      },
      {
        name: "mongoDB",
        color: "green-text-gradient",
      },
      {
        name: "express",
        color: "pink-text-gradient",
      },
    ],
    image: volunteerimage,
    source_code_link: "https://github.com/shashi4263/volunteer",
  },
  {
    name: "Animation",
    description:
      "A 3d animation video using blender where it is rendered using cycles and given a depth of field to surrounding.",
    tags: [
      {
        name: "blender",
        color: "blue-text-gradient",
      },
      {
        name: "cycles",
        color: "green-text-gradient",
      },
      {
        name: "animation",
        color: "pink-text-gradient",
      },
    ],
    image: tripguide,
    source_code_link: "https://github.com/shashi4263/blender",
  },
];

export { services, technologies, experiences, testimonials, projects };
